services:
  # HTTPBin service - a simple HTTP testing service
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - "8080:80"
    networks:
      - kong-net

  # Express.js API service
  express-app:
    build: ./express-app
    container_name: express-app
    ports:
      - "3000:3000"
    networks:
      - kong-net

  kong-database:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migrations:
    build:
      context: .
      dockerfile: Dockerfile.kong-custom
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kongadmin
      KONG_PLUGINS: bundled,request-response-logger
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    build:
      context: .
      dockerfile: Dockerfile.kong-custom
    container_name: kong
    depends_on:
      - kong-migrations
      - kong-database
      - httpbin
      - express-app
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kongadmin
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PLUGINS: bundled,request-response-logger

    ports:
      - "8000:8000"   # Proxy
      - "8443:8443"   # Proxy SSL
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin API SSL
      - "8002:8002"   # Konga UI
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
